spring:
  application:
    name: oathservice
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      open-in-view: false
      ddl-auto: update
server:
  port: 9000
logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"