spring:
  application:
    name: oathservice
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
server:
  port: 9000
logging:
  level:
    root: DEBUG
